# Generated by Django 4.0.4 on 2022-05-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pontuacaoquizz',
            name='nome',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
