# Generated by Django 4.0.4 on 2022-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projeto_alter_blog_autor_alter_blog_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/portfolio/images/'),
        ),
    ]
