# Generated by Django 4.0.4 on 2022-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_blog_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/static/portfolio/images/'),
        ),
    ]
